/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.stacktrace;

public class Library {
    public static void main(String[] args) {
    	try {
    		nest1();
    	} catch (Exception e) {
    		System.out.println("Catching error.");
    		e.printStackTrace();
    	}
    	nest1();
    	System.out.println("exiting gracefully.");
    	System.exit(0);
    }
    
    private static void nest1() {
    	nest2();
    }
    
    private static void nest2() {
    	nest3();
    }
    
    private static void nest3() {
    	nest4();
    }
    
    private static void nest4() {
    	throw new RuntimeException("exception is here.");
    }
}
